//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScamAlert.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Privilege
    {
        public int privilegeId { get; set; }
        public string privilegeName { get; set; }
        public string privilegeDescription { get; set; }
        public string pointsRequired { get; set; }
    }
}
